### ISSUE TITLE
certus quartz dust

### ISSUE THREAD

**Issue by Kropter** [tfox83/fubarpackissues#5]
* **Resource Pack Version**:  1.4.0

* **Issue**:
Certus Quartz Dust is 2 times in, and it doesn't seem to be by Design.
One is from AE2, the other is from JAOPCA.
The JAOPCA Certus Quartz Dust is totally useless, not used in any meaningful recipe. It limits the machines Certus Quartz Dust from AE2 can be fabricated.
Can they be made interchangeable ? 

* **Known Fix**:

**Comment by tfox83** [comment]
I think next update I will remove JAOPCA, since I am doing custom unification I do not think we need it.  I will do some testing.  If not then I can unify to the AE2 versions of nether quartz/certus quartz dusts.

**Comment by tfox83** [comment]
Fixed in 1.5.0
